version: '3'
services:
  mongo:
    image: mongo
    restart: always
  jguweka:
    image: jguweka/jguweka:OAS3
    restart: always
    links:
      - "mongo:mongodb"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"
networks:
  webnet:
