version: '3'
services:
  mongo:
    image: mongo
    container_name: jguwekamongo
    restart: always
  jguweka:
    image: jguweka/jguweka:OAS3
    restart: always
    environment:
      CATALINA_OPTS: '-agentpath:/usr/local/jprofiler11.0/bin/linux-x64/libjprofilerti.so=port=8849,nowait'
    links:
      - "mongo:mongodb"
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"
    ports:
      - "8080"
  nginx:
    image: nginx:latest
    container_name: lb
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - jguweka 

